version: '3.8'

services:
  footapp_postgres:
    image: postgres:15-alpine
    container_name: footapp_postgres
    environment:
      POSTGRES_USER: footapp_user
      POSTGRES_PASSWORD: footapp_password
      POSTGRES_DB: footapp_db
    ports:
      - '5432:5432'
    volumes:
      - footapp_pg_data:/var/lib/postgresql/data

volumes:
  footapp_pg_data:
